In [8]:
import sys
sys.path.append('/software/pc24403/tfpcbpggsz')  
from core import *


In [9]:
from importlib.machinery import SourceFileLoader
config_mass_shape_output = SourceFileLoader('config_mass_shape_output', '/software/pc24403/PCBPGGSZ/outputs/toy/mass_fit/config/%s'%('config_mass_shape_output_1.py')).load_module()

varDict = config_mass_shape_output.getconfig()

Bu_M = {}
mass_pdfs = {}
pdfs_data = {}
for decay in ['b2dk_LL', 'b2dk_DD']:
    for charge in ['p', 'm']:
        Bu_M[decay+'_'+charge] = np.linspace(5080.0, 5800, 1000000)
        Bu_M[decay+'_'+charge] = tf.cast(Bu_M[decay+'_'+charge], tf.float64)
        pdfs_data[decay+'_'+charge] = preparePdf_data(varDict, decay)

--- Constructing signal pdfs...
--- Constructing misID pdfs...
--- Constructing low-mass pdfs...
--- Constructing comb pdfs...
--- INFO: Writing to file...
--- Constructing signal pdfs...
--- Constructing misID pdfs...
--- Constructing low-mass pdfs...
--- Constructing comb pdfs...
--- INFO: Writing to file...
--- Constructing signal pdfs...
--- Constructing misID pdfs...
--- Constructing low-mass pdfs...
--- Constructing comb pdfs...
--- INFO: Writing to file...
--- Constructing signal pdfs...
--- Constructing misID pdfs...
--- Constructing low-mass pdfs...
--- Constructing comb pdfs...
--- INFO: Writing to file...


In [10]:
comps = ['sig', 'misid', 'comb', 'low', 'low_misID', 'low_Bs2DKPi']
for decay in ['b2dk_LL', 'b2dk_DD']:
    for charge in ['p', 'm']:
        new_decay = decay + '_'+ charge
        mass_pdfs[new_decay] = {}
        for comp in comps:
            if decay.split('_')[0] == 'b2dpi' and (comp == 'low_Bs2DKPi' or comp == 'low_misID'): continue
            mass_pdfs[new_decay][comp] = pdfs_data[new_decay][comp](Bu_M[new_decay])

In [12]:
mass_pdfs

{'b2dk_LL_p': {'sig': <tf.Tensor: shape=(1000000,), dtype=float64, numpy=
  array([3.71886047e-05, 3.71887431e-05, 3.71888814e-05, ...,
         5.55346309e-07, 5.55342700e-07, 5.55339091e-07])>,
  'misid': <tf.Tensor: shape=(1000000,), dtype=float64, numpy=
  array([1.84286350e-16, 1.84319246e-16, 1.84352147e-16, ...,
         1.89214859e-05, 1.89213634e-05, 1.89212409e-05])>,
  'comb': <tf.Tensor: shape=(1000000,), dtype=float64, numpy=
  array([0.00368716, 0.00368715, 0.00368714, ..., 0.00032843, 0.00032843,
         0.00032843])>,
  'low': <tf.Tensor: shape=(1000000,), dtype=float64, numpy=
  array([1.41777977e-002, 1.41782039e-002, 1.41786102e-002, ...,
         3.87169771e-129, 3.86981887e-129, 3.86794094e-129])>,
  'low_misID': <tf.Tensor: shape=(1000000,), dtype=float64, numpy=
  array([6.79754460e-03, 6.79750357e-03, 6.79746254e-03, ...,
         1.21173847e-06, 1.21172703e-06, 1.21171559e-06])>,
  'low_Bs2DKPi': <tf.Tensor: shape=(1000000,), dtype=float64, numpy=
  array([0.0

In [16]:
Bu_M_old = np.load('/shared/scratch/pc24403/amp_ampgen_noeff/Bu_M_mc_noeff.npy', allow_pickle=True).item()

(5000000,)

In [19]:
for key in Bu_M_old.keys():
    if 'b2dk' in key:
        Bu_M_old[key] = Bu_M[key]

In [20]:
np.save('/shared/scratch/pc24403/amp_ampgen_noeff/Bu_M_mc_noeff.npy', Bu_M_old)