In [1]:

from tfpcbpggsz.tensorflow_wrapper import *
import numpy as np
import uproot as up

from tfpcbpggsz.generator.phasespace import PhaseSpaceGenerator
from tfpcbpggsz.ulti import get_mass, phsp_to_srd
from matplotlib import pyplot as plt
from tfpcbpggsz.generator.generator import GenTest, BaseGenerator, ARGenerator
from tfpcbpggsz.generator.data import data_mask, data_merge, data_shape
from tfpcbpggsz.amp_test import *
from tfpcbpggsz.generator.gen_pcbpggsz import pcbpggsz_generator

2024-07-31 14:29:12.270541: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/software/pc24403/tfpcbpggsz/tfpcbpggsz/generator/tensorflow_wrapper.py:57: UserWarning: arctan2 already exists.
  warnings.warn("{} already exists.".format(name))


In [2]:

pcgen = pcbpggsz_generator()


D0ToKSpipi2018 (Apr 30 2024) ==> Initialization !


In [3]:
pcgen.type = 'b2dh'

In [4]:
fun = pcgen.formula()

In [5]:
fun

<bound method pcbpggsz_generator.b2dh of <tfpcbpggsz.generator.gen_pcbpggsz.pcbpggsz_generator object at 0x7f6c284308f0>>

In [7]:
pcgen.generate(1000, type="b2dh", rb=0.1, deltaB=0.1, gamma=0.1)

[<tf.Tensor: shape=(1222, 4), dtype=float64, numpy=
array([[ 0.78355464, -0.22174822,  0.56045004, -0.05533221],
       [ 0.9124431 ,  0.56840427, -0.2960289 , -0.41739214],
       [ 0.60951816,  0.00273255,  0.0155118 ,  0.35163136],
       ...,
       [ 0.8704056 , -0.63341604, -0.28399079, -0.1676889 ],
       [ 0.79268796,  0.1606643 ,  0.27270122, -0.52967494],
       [ 0.77685012, -0.02769006,  0.35007677, -0.48224054]])>, <tf.Tensor: shape=(1222, 4), dtype=float64, numpy=
array([[ 0.49006325,  0.05295101, -0.16518918,  0.43656715],
       [ 0.53026874, -0.18390371,  0.1935077 ,  0.43639351],
       [ 0.49504381, -0.35527536,  0.11069575,  0.29515149],
       ...,
       [ 0.35505287,  0.1536771 ,  0.18678894, -0.21926228],
       [ 0.37876476,  0.23920642,  0.16526428,  0.19862253],
       [ 0.28366866,  0.04753759,  0.237386  , -0.04874566]])>, <tf.Tensor: shape=(1222, 4), dtype=float64, numpy=
array([[ 0.5912221 ,  0.16879721, -0.39526086, -0.38123495],
       [ 0.42212814, -0

2024-07-31 14:31:41.258327: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Shapes of all inputs must match: values[0].shape = [1222] != values[1].shape = [1222,3]


InvalidArgumentError: {{function_node __wrapped__Pack_N_2_device_/job:localhost/replica:0/task:0/device:GPU:0}} Shapes of all inputs must match: values[0].shape = [1222] != values[1].shape = [1222,3] [Op:Pack] name: stack

In [56]:
import tensorflow as tf
import numpy as np
p1=np.array([[0.7, 0.3, -0.3, -0.1],[0.7, 0.2, -0.3, -0.1]])
tf.cast(p1, tf.float32)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.7,  0.3, -0.3, -0.1],
       [ 0.7,  0.2, -0.3, -0.1]], dtype=float32)>

In [57]:
p1

array([[ 0.7,  0.3, -0.3, -0.1],
       [ 0.7,  0.2, -0.3, -0.1]])

In [62]:
# Ensure negative values for the specified columns
p1_tf_modified = tf.concat([
    p1[:, :1], 
    tf.negative(p1[:, 1:]) 
], axis=1)

print(p1_tf_modified) 

tf.Tensor(
[[ 0.7 -0.3  0.3  0.1]
 [ 0.7 -0.2  0.3  0.1]], shape=(2, 4), dtype=float64)


In [54]:
p1[0]

[0.7, 0.3, -0.3, -0.1]

In [40]:
[p1[0][:], tf.negative(p1[1:][:])]

[[0.7, 0.3, -0.3, -0.1],
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[-0.7, -0.2,  0.3,  0.1]], dtype=float32)>]

In [27]:
result = tf.concat([p1[:][0], p1[:][1:]], axis=0)


2024-07-31 14:48:08.526147: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: ConcatOp : Ranks of all input tensors should match: shape[0] = [4] vs. shape[1] = [1,4]


InvalidArgumentError: {{function_node __wrapped__ConcatV2_N_2_device_/job:localhost/replica:0/task:0/device:GPU:0}} ConcatOp : Ranks of all input tensors should match: shape[0] = [4] vs. shape[1] = [1,4] [Op:ConcatV2]